export type SortingState = {
  array: number[];
  currentIndex?: number;
  heapRange?: [number, number];
  keyIndex?: number;
  minimumIndex?: number;
  maximumIndex?: number;
  searchRange?: [number, number];
  scanningIndex?: number;
  shiftedIndices?: number[];
  comparingIndices?: number[];
  swappingIndices?: number[];
  sortedIndices?: number[];
  pivotIndex?: number;
  partitionRange?: [number, number];
  mergeRange?: [number, number];
  leftRange?: [number, number];
  rightRange?: [number, number];
  writeIndex?: number;
};
